---
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/nathandines/stack
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: make deps
      - run: make test
      - run: make
